### ISSUE TITLE
Docker Startup question for onFHIR

### ISSUE THREAD

**Issue by beanformer** [fair4health/common-data-model#2]
We switched to the Docker-based install of onFHIR. We had to adjust the following for onFHIR to start: In `docker/sample-setup/conf/application-docker.conf` we commented out the following:
#conformance-path = "/fhir/conf/conformance.xml
#profiles-path = "/fhir/conf/profiles

If we comment in these two entries, errors will occur. Probably the statements in this conformance.xml or in the files under "profiles" do not match the current version that you build via the git-repo? But there are no updated versions of these files in git.

Of course, commenting it out also causes problems...

**Comment by sinaci** [comment]
onFHIR needs a conformance statement to start up and configure itself. Hence, the file is required. You can put the conformance.xml (and the profiles if you need) into the docker build. Or, you can create a volume mapping to the host machine which includes the conformance.xml.

You can check the onfhir repository to see an example docker setup:
https://github.com/srdc/onfhir/tree/master/docker

**Comment by beanformer** [comment]
I wasn't very precise. If we build the image in the normal way, we get the following error when running `docker-compose up --build` (some lines more for seeing the context):

```
mongo_1   | 2020-09-23T14:05:43.005+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
onfhir_1  | JarClassLoader: Warning: io/onfhir/config/AuthzConfig.class in lib/onfhir-core-3.0.jar is hidden by lib/onfhir-common-3.0.jar (with different bytecode)
onfhir_1  | 2020-09-23_14:05:46.994 [main] INFO  i.o.r.c.FhirR4Configurator - Reading base FHIR foundation resources (base standard) to start configuration of onFhir server ...
onfhir_1  | 2020-09-23_14:05:47.008 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type StructureDefinition from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:47.873 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type StructureDefinition from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:47.997 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type StructureDefinition from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:48.251 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type StructureDefinition from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:48.517 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type SearchParameter from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:48.796 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type ValueSet,CodeSystem from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:49.112 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type ValueSet,CodeSystem from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:49.619 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type ValueSet,CodeSystem from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:49.918 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type OperationDefinition from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:50.235 [main] INFO  i.o.a.u.IOUtil$ - Reading resources of type CompartmentDefinition from default path 'definitions.json.zip'
onfhir_1  | 2020-09-23_14:05:50.561 [main] INFO  i.o.r.c.FhirR4Configurator - Reading FHIR foundation resources to start configuration of onFhir server ...
onfhir_1  | 2020-09-23_14:05:50.562 [main] INFO  i.o.a.u.IOUtil$ - Reading a CapabilityStatement from '/fhir/conf/conformance.xml'
onfhir_1  | Exception in thread "main" java.lang.reflect.InvocationTargetException
onfhir_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
onfhir_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
onfhir_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
onfhir_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
onfhir_1  |     at com.simontuffs.onejar.Boot.run(Boot.java:340)
onfhir_1  |     at com.simontuffs.onejar.Boot.main(Boot.java:166)
onfhir_1  | Caused by: io.onfhir.exception.InitializationException: Cannot read resource CapabilityStatement from path /fhir/conf/conformance.xml!
onfhir_1  |     at io.onfhir.api.util.IOUtil$.readResource(IOUtil.scala:35)
```

At first I only saw `java.lang.reflect.InvocationTargetException`, which can mean a lot of things but is usually hard to fix for the user. Now when I run it again I see` io.onfhir.exception.InitializationException: Cannot read resource CapabilityStatement from path /fhir/conf/conformance.xml`, which rather indicates a problem with the path or access to the file in our installation.

Unfortunately I currently don't have access to the server where the Docker container is running, but tomorrow we'll check - especially if our configuration with profiles-path is correct.

**Comment by beanformer** [comment]
We found the reason by looking into the source code at `io.onfhir.api.util.IOUtil$.readResource()`. It seems that the onFHIR.R3 version used an XML serialization of CapabilityStatement. Currently, onFHIR.R4 requires a version in JSON. Obviously, that fails because we reference `/fhir/conf/conformance.xml`. If we provide the JSON version, the error disappears.

**Comment by sinaci** [comment]
onFHIR started to accept the configuration files only in JSON format. It seems that we forgot to update that in R3, thanks for pointing out.

If it is resolved fir you, can you please close the issue?

**Comment by beanformer** [comment]
Yes, thank you.
